version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "docker"
    directory: "/docker"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "pip"
    directory: "/config"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
