editors:
  opencode:
    install: "npm install -g opencode-ai@${VERSION:-latest}"
    cmd: "opencode"
  claude:
    install: "npm install -g @anthropic-ai/claude-code@${VERSION:-latest}"
    cmd: "claude"
  aider:
    install: "uv tool install aider-chat@${VERSION:-latest}"
    cmd: "aider"
  copilot:
    install: "npm install -g @github/copilot@${VERSION:-latest}"
    cmd: "copilot"
  vibe:
    install: "uv tool install mistral-vibe"
    cmd: "vibe"
  goose:
    install: "uv tool install goose-ai"
    cmd: "goose"
  codex:
    install: "npm i -g @openai/codex@${VERSION:-latest}"
    cmd: "codex"
  gemini:
    install: "npm install -g @google/gemini-cli@${VERSION:-latest}"
    cmd: "gemini"
  cursor:
    install: "curl https://cursor.com/install -fsS | bash && mv /root/.local/bin/agent /usr/local/bin/cursor"
    cmd: "cursor"
